# Docker image
# Build a Docker image to run, deploy, or push to a container registry.
# Add steps that use Docker Compose, tag images, push to a registry, run an image, and more:
# https://docs.microsoft.com/vsts/pipelines/languages/docker

pool:
  vmImage: 'Ubuntu 16.04'

variables:
  COBBLER_DOCKER_IMAGE: 'headmelted/cobbler'
  COBBLER_DOCKER_TAG: 'hybrid-armhf'
  imageName: '$COBBLER_DOCKER_IMAGE:$COBBLER_DOCKER_TAG'

steps:
- displayName: 'Push $COBBLER_DOCKER_TAG to docker hub';
- script: |
    echo "Preparing rootfs";
    . ./build_rootfs.sh;
    echo "Performing first stage image build";
    sudo bash -c "export IMAGE_NAME=$imageName && export DOCKER_TAG=$COBBLER_DOCKER_TAG && . ./hooks/build";

steps:
- displayName: 'Push $COBBLER_DOCKER_TAG to docker hub'
- script: |
    echo "Logging into docker hub";
    docker login -u $DOCKER_LOGIN -p $DOCKER_PASSWORD;
    echo "Pushing image to docker hub";
    docker push headmelted/cobbler:$COBBLER_DOCKER_TAG;
