# Docker image
# Build a Docker image to run, deploy, or push to a container registry.
# Add steps that use Docker Compose, tag images, push to a registry, run an image, and more:
# https://docs.microsoft.com/vsts/pipelines/languages/docker

jobs:
- job: 'hybrid_armhf'
  pool:
    vmImage: 'Ubuntu 16.04'
  variables:
    COBBLER_DOCKER_IMAGE: 'headmelted/cobbler'
    COBBLER_DOCKER_TAG: 'hybrid-armhf'
    COBBLER_IMAGE_NAME: '$COBBLER_DOCKER_IMAGE:$COBBLER_DOCKER_TAG'
  steps:
  - script: |
      echo "Preparing rootfs";
      . ./build_rootfs.sh;
      echo "Performing first stage image build";
      sudo bash -c "export IMAGE_NAME=$COBBLER_IMAGE_NAME && export DOCKER_TAG=$COBBLER_DOCKER_TAG && . ./hooks/build";
    displayName: 'Prepare rootfs for ($COBBLER_DOCKER_TAG)'
  - script: |
      echo "Logging into docker hub";
      docker login -u $DOCKER_LOGIN -p $DOCKER_PASSWORD;
      echo "Pushing image to docker hub";
      docker push $COBBLER_IMAGE_NAME;
    displayName: 'Push to Docker Hub ($COBBLER_DOCKER_TAG)';
