# Docker image
# Build a Docker image to run, deploy, or push to a container registry.
# Add steps that use Docker Compose, tag images, push to a registry, run an image, and more:
# https://docs.microsoft.com/vsts/pipelines/languages/docker

jobs:
- job: 'hybrid_armhf'
  pool:
    vmImage: 'Ubuntu 16.04'
  variables:
    COBBLER_DOCKER_IMAGE: "headmelted/cobbler"
    COBBLER_ARCH: "armhf"
    COBBLER_STRATEGY: "hybrid"
    COBBLER_DOCKER_TAG: "$COBBLER_STRATEGY-$COBBLER_ARCH"
    COBBLER_IMAGE_NAME: "$COBBLER_DOCKER_IMAGE:$COBBLER_DOCKER_TAG"
  steps:
  - script: |
      echo "Downloading rootfs from prebootstrap";
      wget -c "https://github.com/headmelted/prebootstrap/releases/download/Oct-18/prebootstrap_stretch_minbase_$COBBLER_ARCH_rootfs.tar.gz" -O - | tar -xz
      echo "Performing first stage image build";
      sudo bash -c "export IMAGE_NAME=$COBBLER_DOCKER_IMAGE && export DOCKER_TAG=$COBBLER_DOCKER_TAG && . ./hooks/build";
      echo "Logging into docker hub";
      docker login --username $DOCKER_LOGIN -password $DOCKER_PASSWORD;
      echo "Pushing image to docker hub";
      docker push $COBBLER_IMAGE_NAME;
