echo "Setting environment for amd64";
LABEL='amd64_linux';
CROSS_TOOLCHAIN='false';
ARCH='amd64';
RPM_ARCH='x86_64';
NPM_ARCH='x64';
GNU_TRIPLET='x86_64-linux-gnu';
GNU_MULTILIB_TRIPLET='';
CXX='g++';
CC='gcc';
PACKAGE_ARCH='x64';
QEMU_ARCH='amd64';
ELECTRON_ARCH='amd64';
VSCODE_ELECTRON_PLATFORM='amd64';
