echo "Setting environment for s390x";
LABEL="s390x_linux";
CROSS_TOOLCHAIN="true";
ARCH="s390x";
RPM_ARCH="s390x";
NPM_ARCH="";
GNU_TRIPLET="s390x-linux-gnu";
GNU_MULTILIB_TRIPLET="";
CXX="s390x-linux-gnu-g++";
CC="s390x-linux-gnu-gcc";
PACKAGE_ARCH="s390x";
QEMU_PACKAGE_ARCH="s390x";
QEMU_ARCH="s390x";
ELECTRON_ARCH="";
VSCODE_ELECTRON_PLATFORM="";
