export ARCHIE_LABEL="s390x_linux";
export ARCHIE_CROSS_TOOLCHAIN="true";
export ARCHIE_ARCH="s390x";
export ARCHIE_RPM_ARCH="s390x";
export ARCHIE_GNU_TRIPLET="s390x-linux-gnu";
export ARCHIE_HEADERS_GNU_TRIPLET="s390x-linux-gnu";
export ARCHIE_GNU_MULTILIB_TRIPLET="";
export ARCHIE_PACKAGE_ARCH="s390x";
export ARCHIE_QEMU_PACKAGE_ARCH="s390x";
export ARCHIE_QEMU_ARCH="s390x";
export ARCHIE_ELECTRON_ARCH="";

export VSCODE_ELECTRON_PLATFORM="";
