# build_containers.yml

# This file contains the matrix of different architecture and strategy combinations
# we want to produce archie containers for.

jobs:
- template: build_for_arch_and_strategy.yml
# - template: build_all_for_arch.yml
#   parameters:
#     arch: amd64 
# - template: build_all_for_arch.yml
#   parameters:
#     arch: arm64
# - template: build_all_for_arch.yml
#   parameters:
#     arch: armel
# - template: build_all_for_arch.yml
#   parameters:
#     arch: armhf
# - template: build_all_for_arch.yml
#   parameters:
#     arch: i386
# - template: build_all_for_arch.yml
#   parameters:
#     arch: mips
# - template: build_all_for_arch.yml
#   parameters:
#     arch: mips64el
# - template: build_all_for_arch.yml
#   parameters:
#     arch: mipsel
#- template: debootstrap_architecture_template.yml   # debootstrap having trouble with ppc64le, will restore later
#  parameters:
#    arch: ppc64el
#- template: build_all_for_arch.yml
#  parameters:
#    arch: s390x
