#!/bin/sh

if [ -z "${DOCKER_TAG}" ] || [ "${DOCKER_TAG}" == "base" ]; then
  DOCKER_TAG="base"
  FROM_IMAGE="debian:stretch-slim";
  COBBLER_STRATEGY=""
  COBBLER_ARCH=""
else
  FROM_IMAGE="headmelted/cobbler:base";
fi;

docker build --build-arg DOCKER_TAG="$DOCKER_TAG" --build-arg COBBLER_STRATEGY="$COBBLER_STRATEGY" --build-arg COBBLER_ARCH="$COBBLER_ARCH" --build-arg FROM_IMAGE="${FROM_IMAGE}" -t $IMAGE_NAME:$DOCKER_TAG .
