# These are the steps used in a container-based build in VSTS.
jobs:
- job: ${{ parameters.job }}
  displayName: ${{ parameters.arch }}
  pool:
    vmImage: 'Ubuntu 16.04'
  variables:
    ARCHIE_ARCH: ${{ parameters.arch }}
    ARCHIE_STRATEGY: ${{ parameters.strategy }}
    ARCHIE_HOST_DEPENDENCIES: ${{ parameters.dependencies.host }}
    ARCHIE_TARGET_DEPENDENCIES: ${{ parameters.dependencies.target }}
  steps:
  - bash: |
      
      docker_image="headmelted/archie:base"
    
      # Run the container unconfined and with CAP_SYS_ADMIN, for bind mounts
      echo "Binding workspace and executing script for [${ARCHIE_STRATEGY}/${ARCHIE_ARCH}]";
      
      docker run \
        --security-opt apparmor:unconfined --cap-add SYS_ADMIN \
        -e GITHUB_TOKEN=$(GITHUB_TOKEN) \
        -e ARCHIE_STRATEGY \
        -e ARCHIE_ARCH \
        -e ARCHIE_HOST_DEPENDENCIES \
        -e ARCHIE_TARGET_DEPENDENCIES \
        -v $(pwd):/root/build \
        -v $(Build.ArtifactStagingDirectory):/root/output \
        $docker_image /bin/bash -c "cd /root/build && . /root/kitchen/tools/archie_initialize.sh && . /root/kitchen/tools/archie_start_build.sh";
  - task: PublishBuildArtifacts@1
  
